import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  SIGNATURE_REQUEST_OBJECT_UNIVERSAL_IDENTIFIER,
  SR_COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  SR_ERROR_MESSAGE_FIELD_UNIVERSAL_IDENTIFIER,
  SR_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SR_PROVIDER_DOCUMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
  SR_ENVIRONMENT_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SIGNING_URL_EXPIRES_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SIGNING_URL_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SOURCE_ATTACHMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
  SR_SOURCE_FILE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SR_STATUS_COMPLETED,
  SR_STATUS_DECLINED,
  SR_STATUS_EXPIRED,
  SR_STATUS_FAILED,
  SR_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_COMPLETED_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_FAILED_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_PENDING_UNIVERSAL_IDENTIFIER,
  SR_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
  SR_STATUS_PENDING,
  SR_STATUS_SENT,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SIGNATURE_REQUEST_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'signatureRequest',
  namePlural: 'signatureRequests',
  labelSingular: 'Signature request',
  labelPlural: 'Signature requests',
  description:
    'A document sent to Autosignly for electronic signature. Created by the app when a document goes out, never by hand: use Send for signature on the record the document belongs to.',
  icon: 'IconSignature',
  // Nothing here is worth typing by hand. A request created from this screen
  // has no document behind it and no record to hang off, so it would sit in the
  // list as an empty row forever, and an edited field would be overwritten by
  // the next delivery from Autosignly. Deleting still works.
  isUICreatable: false,
  isUIEditable: false,
  labelIdentifierFieldMetadataUniversalIdentifier:
    SR_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: SR_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Document name as it appears to the signers.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: SR_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Where this request stands.',
      icon: 'IconProgress',
      defaultValue: `'${SR_STATUS_PENDING}'`,
      options: [
        {
          id: SR_STATUS_OPTION_PENDING_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_PENDING,
          label: 'Pending',
          color: 'gray',
          position: 0,
        },
        {
          id: SR_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_SENT,
          label: 'Sent',
          color: 'blue',
          position: 1,
        },
        {
          id: SR_STATUS_OPTION_COMPLETED_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_COMPLETED,
          label: 'Completed',
          color: 'green',
          position: 2,
        },
        {
          id: SR_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_DECLINED,
          label: 'Declined',
          color: 'red',
          position: 3,
        },
        {
          id: SR_STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_EXPIRED,
          label: 'Expired',
          color: 'orange',
          position: 4,
        },
        {
          id: SR_STATUS_OPTION_FAILED_UNIVERSAL_IDENTIFIER,
          value: SR_STATUS_FAILED,
          label: 'Failed',
          color: 'red',
          position: 5,
        },
      ],
    },
    {
      universalIdentifier: SR_PROVIDER_DOCUMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'autosignlyDocumentId',
      label: 'Autosignly document ID',
      description: 'Identifier of the document in Autosignly.',
      icon: 'IconHash',
    },
    {
      universalIdentifier: SR_SOURCE_FILE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceFileName',
      label: 'Source file',
      description: 'The attachment that was sent for signature.',
      icon: 'IconPaperclip',
    },
    {
      universalIdentifier: SR_SOURCE_ATTACHMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceAttachmentId',
      label: 'Source attachment',
      description:
        'Identifier of the attachment that was sent, so the same file is not sent twice while a request is still open.',
      icon: 'IconPaperclip',
    },
    {
      universalIdentifier: SR_SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'signedDocument',
      label: 'Signed document',
      description: 'The signed PDF, written back when every signer is done.',
      icon: 'IconFileTypePdf',
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      universalIdentifier: SR_SIGNING_URL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.LINKS,
      name: 'signingLink',
      label: 'Sandbox signing link',
      description:
        'Direct signing page for the signer whose turn it is. A sandbox emails nobody, so this is the only way in; in production Autosignly returns no link here and emails each signer their own.',
      icon: 'IconLink',
    },
    {
      universalIdentifier: SR_SIGNING_URL_EXPIRES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'signingLinkExpiresAt',
      label: 'Link expires at',
      description: 'When the signing link stops working.',
      icon: 'IconClockHour4',
    },
    {
      universalIdentifier: SR_ENVIRONMENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'environment',
      label: 'Environment',
      description: 'PROD or SANDBOX, taken from the API key that sent it.',
      icon: 'IconFlask',
    },
    {
      universalIdentifier: SR_SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'sentAt',
      label: 'Sent at',
      description: 'When the document went out for signature.',
      icon: 'IconSend',
    },
    {
      universalIdentifier: SR_COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'completedAt',
      label: 'Completed at',
      description: 'When the request reached a final state.',
      icon: 'IconCalendarCheck',
    },
    {
      universalIdentifier: SR_ERROR_MESSAGE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'errorMessage',
      label: 'Error',
      description: 'Why the request failed, when it did.',
      icon: 'IconAlertTriangle',
    },
  ],
});
