import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  SG_COUNTRY_FIELD_UNIVERSAL_IDENTIFIER,
  SG_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
  SG_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SG_ORDER_FIELD_UNIVERSAL_IDENTIFIER,
  SG_PHONE_FIELD_UNIVERSAL_IDENTIFIER,
  SG_SIGNATURE_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  SG_SIGNED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  SG_STATUS_DECLINED,
  SG_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  SG_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
  SG_STATUS_OPTION_PENDING_UNIVERSAL_IDENTIFIER,
  SG_STATUS_OPTION_SIGNED_UNIVERSAL_IDENTIFIER,
  SG_STATUS_PENDING,
  SG_STATUS_SIGNED,
  SG_VERIFICATION_METHOD_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNER_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SIGNER_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'documentSigner',
  namePlural: 'documentSigners',
  labelSingular: 'Signer',
  labelPlural: 'Signers',
  description:
    'One person asked to sign a document. Written by the app from the signature request, never by hand.',
  icon: 'IconUserCheck',
  isUICreatable: false,
  isUIEditable: false,
  labelIdentifierFieldMetadataUniversalIdentifier:
    SG_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: SG_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Full name of the signer.',
      icon: 'IconUser',
    },
    {
      universalIdentifier: SG_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'email',
      label: 'Email',
      description: 'Where the signing invitation is sent.',
      icon: 'IconMail',
    },
    {
      universalIdentifier: SG_COUNTRY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'country',
      label: 'Country',
      description:
        'ISO 3166-1 alpha-2 code. Decides which signature policy applies.',
      icon: 'IconFlag',
    },
    {
      universalIdentifier: SG_PHONE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'phoneNumber',
      label: 'Phone number',
      description: 'E.164 number, required when identity is verified by SMS.',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: SG_SIGNATURE_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'signatureType',
      label: 'Signature type',
      description: 'Signature level asked of this signer.',
      icon: 'IconCertificate',
    },
    {
      universalIdentifier: SG_VERIFICATION_METHOD_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'verificationMethod',
      label: 'Verification method',
      description: 'How this signer confirms their identity.',
      icon: 'IconShieldCheck',
    },
    {
      universalIdentifier: SG_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Whether this signer is done.',
      icon: 'IconProgress',
      defaultValue: `'${SG_STATUS_PENDING}'`,
      options: [
        {
          id: SG_STATUS_OPTION_PENDING_UNIVERSAL_IDENTIFIER,
          value: SG_STATUS_PENDING,
          label: 'Pending',
          color: 'gray',
          position: 0,
        },
        {
          id: SG_STATUS_OPTION_SIGNED_UNIVERSAL_IDENTIFIER,
          value: SG_STATUS_SIGNED,
          label: 'Signed',
          color: 'green',
          position: 1,
        },
        {
          id: SG_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
          value: SG_STATUS_DECLINED,
          label: 'Declined',
          color: 'red',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier: SG_ORDER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'signingOrder',
      label: 'Order',
      description: 'Position in the signing order, starting at 1.',
      icon: 'IconSortAscending',
    },
    {
      universalIdentifier: SG_SIGNED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'signedAt',
      label: 'Signed at',
      description: 'When this signer finished.',
      icon: 'IconCalendarCheck',
    },
  ],
});
